CREATE TABLE `Invoice` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `userId` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `amountDue` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT '0.00',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `paymentStatus` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `FK_invoice_user` (`userId`),
  CONSTRAINT `FK_invoice_user` FOREIGN KEY (`userId`) REFERENCES `User` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;