CREATE TABLE `User` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL DEFAULT '',
  `password` VARCHAR(128) NOT NULL DEFAULT '',
  `salt` VARCHAR(8) NOT NULL DEFAULT '',
  `firstName` VARCHAR(50) NOT NULL DEFAULT '',
  `surname` VARCHAR(50) NOT NULL DEFAULT '',
  `phone` VARCHAR(15) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) COLLATE='utf8_general_ci' ENGINE=InnoDB;